apiVersion: v1
kind: Service
metadata:
  name: corebanking-svc
spec:
  selector:
    app: corebanking
  ports:
    - name: http
      port: 8088
      protocol: TCP
      targetPort: 8088
  type: LoadBalancer

